// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const completeTodo = `-- name: CompleteTodo :one
UPDATE todos
SET completed = 1, completed_at = ?, updated_at = ?
WHERE id = ?
RETURNING id
`

type CompleteTodoParams struct {
	CompletedAt sql.NullTime `json:"completed_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	ID          int64        `json:"id"`
}

func (q *Queries) CompleteTodo(ctx context.Context, arg CompleteTodoParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, completeTodo, arg.CompletedAt, arg.UpdatedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (name,  completed, priority, tag, completed_at, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, name, completed, completed_at, created_at, updated_at, priority, tag
`

type CreateTodoParams struct {
	Name        string         `json:"name"`
	Completed   bool           `json:"completed"`
	Priority    string         `json:"priority"`
	Tag         sql.NullString `json:"tag"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.Name,
		arg.Completed,
		arg.Priority,
		arg.Tag,
		arg.CompletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Priority,
		&i.Tag,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = ?
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const getAllTodo = `-- name: GetAllTodo :many
SELECT id, name, completed, completed_at, created_at, updated_at, priority, tag FROM todos
`

func (q *Queries) GetAllTodo(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getAllTodo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Priority,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTodos = `-- name: GetAllTodos :many
SELECT id, name, completed, completed_at, created_at, updated_at, priority, tag FROM todos
ORDER BY created_at DESC
`

func (q *Queries) GetAllTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getAllTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Priority,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodoById = `-- name: GetTodoById :one
SELECT id, name, completed, completed_at, created_at, updated_at, priority, tag FROM todos
WHERE id = ?
`

func (q *Queries) GetTodoById(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoById, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Priority,
		&i.Tag,
	)
	return i, err
}

const getTodoCountById = `-- name: GetTodoCountById :one
SELECT COUNT(*) AS found
FROM todos 
WHERE id = ?
`

func (q *Queries) GetTodoCountById(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTodoCountById, id)
	var found int64
	err := row.Scan(&found)
	return found, err
}

const markTodoComplete = `-- name: MarkTodoComplete :exec
UPDATE todos
SET completed = 1, completed_at = ?, updated_at = ?
WHERE id = ?
`

type MarkTodoCompleteParams struct {
	CompletedAt sql.NullTime `json:"completed_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	ID          int64        `json:"id"`
}

func (q *Queries) MarkTodoComplete(ctx context.Context, arg MarkTodoCompleteParams) error {
	_, err := q.db.ExecContext(ctx, markTodoComplete, arg.CompletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateTodo = `-- name: UpdateTodo :exec
UPDATE todos
SET name = ?, completed = ?, completed_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateTodoParams struct {
	Name        string       `json:"name"`
	Completed   bool         `json:"completed"`
	CompletedAt sql.NullTime `json:"completed_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	ID          int64        `json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.ExecContext(ctx, updateTodo,
		arg.Name,
		arg.Completed,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
