// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const completeTodo = `-- name: CompleteTodo :one
UPDATE todos
SET completed = 1, completed_at = ?, updated_at = ?
WHERE id = ?
RETURNING id
`

type CompleteTodoParams struct {
	CompletedAt sql.NullTime `json:"completed_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	ID          int64        `json:"id"`
}

func (q *Queries) CompleteTodo(ctx context.Context, arg CompleteTodoParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, completeTodo, arg.CompletedAt, arg.UpdatedAt, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (name,  completed, priority, tag, completed_at, created_at, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
RETURNING id, name, completed, completed_at, created_at, updated_at, priority, tag
`

type CreateTodoParams struct {
	Name        string         `json:"name"`
	Completed   bool           `json:"completed"`
	Priority    string         `json:"priority"`
	Tag         sql.NullString `json:"tag"`
	CompletedAt sql.NullTime   `json:"completed_at"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.Name,
		arg.Completed,
		arg.Priority,
		arg.Tag,
		arg.CompletedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Completed,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Priority,
		&i.Tag,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = ?
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const getAllTodo = `-- name: GetAllTodo :many
SELECT id, name, completed, completed_at, created_at, updated_at, priority, tag FROM todos
`

func (q *Queries) GetAllTodo(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getAllTodo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Priority,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllTodos = `-- name: GetAllTodos :many
SELECT id, name, completed, completed_at, created_at, updated_at, priority, tag FROM todos
WHERE (CAST(?1 AS TEXT) IS NOT NULL OR CAST(?1 AS TEXT) IS NULL)
ORDER BY 
  CASE WHEN CAST(?1 AS TEXT) = 'priority' THEN priority END DESC,
  CASE WHEN CAST(?1 AS TEXT) = 'created_at' THEN created_at END DESC,
  id DESC
LIMIT ?3 
OFFSET ?2
`

type GetAllTodosParams struct {
	SortBy string `json:"sort_by"`
	Offset int64  `json:"offset"`
	Limit  int64  `json:"limit"`
}

func (q *Queries) GetAllTodos(ctx context.Context, arg GetAllTodosParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getAllTodos, arg.SortBy, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Priority,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingTodos = `-- name: GetPendingTodos :many
SELECT id, name, completed, completed_at, created_at, updated_at, priority, tag FROM todos
WHERE
 CASE WHEN ?1 = 1 THEN completed = 1
      WHEN ?2 = 1 THEN completed = 0
      ELSE 1=1 END 
 AND (CAST(?3 AS TEXT) IS NOT NULL OR CAST(?3 AS TEXT) IS NULL)
ORDER BY 
  CASE WHEN CAST(?3 AS TEXT) = 'priority' THEN priority END DESC,
  CASE WHEN CAST(?3 AS TEXT) = 'created_at' THEN created_at END DESC,
  id DESC
LIMIT ?5 
OFFSET ?4
`

type GetPendingTodosParams struct {
	Completed interface{} `json:"completed"`
	Pending   interface{} `json:"pending"`
	SortBy    string      `json:"sort_by"`
	Offset    int64       `json:"offset"`
	Limit     int64       `json:"limit"`
}

func (q *Queries) GetPendingTodos(ctx context.Context, arg GetPendingTodosParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getPendingTodos,
		arg.Completed,
		arg.Pending,
		arg.SortBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Priority,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodoByPriority = `-- name: GetTodoByPriority :many
SELECT id, name, completed, completed_at, created_at, updated_at, priority, tag FROM todos
WHERE
  CASE WHEN ?1 IS NOT NULL THEN priority = ?1
        ELSE 1=1 END
  AND (CAST(?2 AS TEXT) IS NOT NULL OR CAST(?2 AS TEXT) IS NULL)
ORDER BY 
  CASE WHEN CAST(?2 AS TEXT) = 'priority' THEN priority END DESC,
  CASE WHEN CAST(?2 AS TEXT) = 'created_at' THEN created_at END DESC,
  id DESC
LIMIT ?4 
OFFSET ?3
`

type GetTodoByPriorityParams struct {
	Priority interface{} `json:"priority"`
	SortBy   string      `json:"sort_by"`
	Offset   int64       `json:"offset"`
	Limit    int64       `json:"limit"`
}

func (q *Queries) GetTodoByPriority(ctx context.Context, arg GetTodoByPriorityParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodoByPriority,
		arg.Priority,
		arg.SortBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Priority,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodoCountById = `-- name: GetTodoCountById :one
SELECT COUNT(*) AS found
FROM todos 
WHERE id = ?
`

func (q *Queries) GetTodoCountById(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTodoCountById, id)
	var found int64
	err := row.Scan(&found)
	return found, err
}

const getTodosByFiltersByCreatedAt = `-- name: GetTodosByFiltersByCreatedAt :many
WITH config AS (SELECT CAST(?8 AS INTEGER) AS is_desc)
SELECT id, name, completed, completed_at, created_at, updated_at, priority, tag FROM todos 
WHERE 
  -- Filter by completion status
  CASE 
    WHEN ?1 = 1 THEN TRUE
    WHEN ?2 = 1 THEN completed = 1
    WHEN ?3 = 1 THEN completed = 0
    ELSE TRUE
  END
  -- Filter by priority
  AND CASE 
    WHEN ?4 IS NOT NULL THEN priority = ?4
    ELSE TRUE
  END
  -- Filter by tag
  AND CASE 
    WHEN ?5 IS NOT NULL THEN tag = ?5
    ELSE TRUE
  END
ORDER BY 
  CASE WHEN (SELECT is_desc FROM config) = 1 THEN created_at END DESC,
  CASE WHEN (SELECT is_desc FROM config) = 0 THEN created_at END ASC,
  id DESC
LIMIT ?7 
OFFSET ?6
`

type GetTodosByFiltersByCreatedAtParams struct {
	All       interface{} `json:"all"`
	Completed interface{} `json:"completed"`
	Pending   interface{} `json:"pending"`
	Priority  interface{} `json:"priority"`
	Tag       interface{} `json:"tag"`
	Offset    int64       `json:"offset"`
	Limit     int64       `json:"limit"`
	IsDesc    int64       `json:"is_desc"`
}

func (q *Queries) GetTodosByFiltersByCreatedAt(ctx context.Context, arg GetTodosByFiltersByCreatedAtParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByFiltersByCreatedAt,
		arg.All,
		arg.Completed,
		arg.Pending,
		arg.Priority,
		arg.Tag,
		arg.Offset,
		arg.Limit,
		arg.IsDesc,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Priority,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodosByFiltersById = `-- name: GetTodosByFiltersById :many
WITH config AS (SELECT CAST(?8 AS INTEGER) AS is_desc)
SELECT id, name, completed, completed_at, created_at, updated_at, priority, tag FROM todos 
WHERE 
  -- Filter by completion status
  CASE 
    WHEN ?1 = 1 THEN TRUE
    WHEN ?2 = 1 THEN completed = 1
    WHEN ?3 = 1 THEN completed = 0
    ELSE TRUE
  END
  -- Filter by priority
  AND CASE 
    WHEN ?4 IS NOT NULL THEN priority = ?4
    ELSE TRUE
  END
  -- Filter by tag
  AND CASE 
    WHEN ?5 IS NOT NULL THEN tag = ?5
    ELSE TRUE
  END
ORDER BY 
  CASE WHEN (SELECT is_desc FROM config) = 1 THEN id END DESC,
  CASE WHEN (SELECT is_desc FROM config) = 0 THEN id END ASC,
  id DESC
LIMIT ?7 
OFFSET ?6
`

type GetTodosByFiltersByIdParams struct {
	All       interface{} `json:"all"`
	Completed interface{} `json:"completed"`
	Pending   interface{} `json:"pending"`
	Priority  interface{} `json:"priority"`
	Tag       interface{} `json:"tag"`
	Offset    int64       `json:"offset"`
	Limit     int64       `json:"limit"`
	IsDesc    int64       `json:"is_desc"`
}

func (q *Queries) GetTodosByFiltersById(ctx context.Context, arg GetTodosByFiltersByIdParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByFiltersById,
		arg.All,
		arg.Completed,
		arg.Pending,
		arg.Priority,
		arg.Tag,
		arg.Offset,
		arg.Limit,
		arg.IsDesc,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Priority,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodosByFiltersByPriority = `-- name: GetTodosByFiltersByPriority :many
WITH config AS (SELECT CAST(?8 AS INTEGER) AS is_desc)
SELECT id, name, completed, completed_at, created_at, updated_at, priority, tag FROM todos 
WHERE 
  -- Filter by completion status
  CASE 
    WHEN ?1 = 1 THEN TRUE
    WHEN ?2 = 1 THEN completed = 1
    WHEN ?3 = 1 THEN completed = 0
    ELSE TRUE
  END
  -- Filter by priority
  AND CASE 
    WHEN ?4 IS NOT NULL THEN priority = ?4
    ELSE TRUE
  END
  -- Filter by tag
  AND CASE 
    WHEN ?5 IS NOT NULL THEN tag = ?5
    ELSE TRUE
  END
ORDER BY 
  CASE WHEN (SELECT is_desc FROM config) = 1 THEN priority END DESC,
  CASE WHEN (SELECT is_desc FROM config) = 0 THEN priority END ASC,
  id DESC
LIMIT ?7 
OFFSET ?6
`

type GetTodosByFiltersByPriorityParams struct {
	All       interface{} `json:"all"`
	Completed interface{} `json:"completed"`
	Pending   interface{} `json:"pending"`
	Priority  interface{} `json:"priority"`
	Tag       interface{} `json:"tag"`
	Offset    int64       `json:"offset"`
	Limit     int64       `json:"limit"`
	IsDesc    int64       `json:"is_desc"`
}

func (q *Queries) GetTodosByFiltersByPriority(ctx context.Context, arg GetTodosByFiltersByPriorityParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByFiltersByPriority,
		arg.All,
		arg.Completed,
		arg.Pending,
		arg.Priority,
		arg.Tag,
		arg.Offset,
		arg.Limit,
		arg.IsDesc,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Priority,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodosByTag = `-- name: GetTodosByTag :many
SELECT id, name, completed, completed_at, created_at, updated_at, priority, tag FROM todos
WHERE
  CASE WHEN ?1 IS NOT NULL THEN tag = ?1
        ELSE 1=1 END
  AND (CAST(?2 AS TEXT) IS NOT NULL OR CAST(?2 AS TEXT) IS NULL)
ORDER BY 
  CASE WHEN CAST(?2 AS TEXT) = 'priority' THEN priority END DESC,
  CASE WHEN CAST(?2 AS TEXT) = 'created_at' THEN created_at END DESC,
  id DESC
LIMIT ?4 
OFFSET ?3
`

type GetTodosByTagParams struct {
	Tag    interface{} `json:"tag"`
	SortBy string      `json:"sort_by"`
	Offset int64       `json:"offset"`
	Limit  int64       `json:"limit"`
}

func (q *Queries) GetTodosByTag(ctx context.Context, arg GetTodosByTagParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByTag,
		arg.Tag,
		arg.SortBy,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Completed,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Priority,
			&i.Tag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTodoComplete = `-- name: MarkTodoComplete :exec
UPDATE todos
SET completed = 1, completed_at = ?, updated_at = ?
WHERE id = ?
`

type MarkTodoCompleteParams struct {
	CompletedAt sql.NullTime `json:"completed_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	ID          int64        `json:"id"`
}

func (q *Queries) MarkTodoComplete(ctx context.Context, arg MarkTodoCompleteParams) error {
	_, err := q.db.ExecContext(ctx, markTodoComplete, arg.CompletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateTodo = `-- name: UpdateTodo :exec
UPDATE todos
SET name = ?, completed = ?, completed_at = ?, updated_at = ?
WHERE id = ?
`

type UpdateTodoParams struct {
	Name        string       `json:"name"`
	Completed   bool         `json:"completed"`
	CompletedAt sql.NullTime `json:"completed_at"`
	UpdatedAt   time.Time    `json:"updated_at"`
	ID          int64        `json:"id"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) error {
	_, err := q.db.ExecContext(ctx, updateTodo,
		arg.Name,
		arg.Completed,
		arg.CompletedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
